packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@types/node': 24.0.0
  dotenv-cli: ^8.0.0
  zod: ^3.25.60

catalogs:
  react:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.6

  tailwind:
    '@tailwindcss/postcss': ^4.1.10
    '@tailwindcss/vite': ^4.1.10
    tailwindcss: ^4.1.10

  tool:
    eslint: ^9.28.0
    prettier: ^3.5.3
    typescript: ^5.8.3
