packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@types/node': 22.15.30
  zod: ^3.25.55

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': 19.1.5
    '@types/react-dom': 19.1.5

  tailwind:
    '@tailwindcss/postcss': ^4.1.8
    '@tailwindcss/vite': ^4.1.8
    tailwindcss: ^4.1.8

  tool:
    eslint: ^9.28.0
    prettier: ^3.5.3
    typescript: ^5.8.3
