packages:
  - apps/*
  - packages/*
  - tools/*

catalogs:
  prod:
    '@tanstack/react-query': ^5.90.19
    zod: ^4.3.5
  dev:
    '@types/node': ^25.0.9
    dotenv-cli: ^11.0.0
    tsdown: ^0.19.0
    typescript: ^5.9.3
  react:
    '@types/react': ^19.2.8
    '@types/react-dom': ^19.2.3
    react: ^19.2.3
    react-dom: ^19.2.3
  tailwind:
    '@tailwindcss/postcss': ^4.1.18
    '@tailwindcss/vite': ^4.1.18
    tailwindcss: ^4.1.18
    uniwind: ^1.2.2
  trpc:
    '@trpc/server': ^11.8.1
    '@trpc/client': ^11.8.1
    '@trpc/tanstack-react-query': ^11.8.1
    superjson": ^2.2.6
  orpc:
    '@orpc/server': ^1.13.4
    '@orpc/client': ^1.13.4
    '@orpc/tanstack-query': ^1.13.4
