packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@types/node': 24.0.15
  dotenv-cli: ^8.0.0
  eslint: ^9.31.0
  prettier: ^3.6.2
  typescript: ^5.8.3

catalogs:
  react:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    react: ^19.1.0
    react-dom: ^19.1.0
  tailwind:
    '@tailwindcss/postcss': ^4.1.11
    '@tailwindcss/vite': ^4.1.11
    tailwindcss: ^4.1.11
